---
- name: Playbook de Seguridad y Hardening para AlmaLinux
  hosts: all
  become: true
  vars:
#    admin_users:
#      - ometeotl

  tasks:
    - name: Asegurar que todos los paquetes estén actualizados a la última versión de seguridad
      dnf:
        name: "*"
        state: latest
        update_cache: true
      become: true

    - name: Configurar parámetros seguros en SSH daemon
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: '/usr/sbin/sshd -t -f %s'
      loop:
        - { regexp: '^#?PermitRootLogin ', line: 'PermitRootLogin no' }
        - { regexp: '^#?X11Forwarding ', line: 'X11Forwarding no' }
        - { regexp: '^#?MaxAuthTries ', line: 'MaxAuthTries 3' }
        - { regexp: '^#?ClientAliveInterval ', line: 'ClientAliveInterval 300' }
        - { regexp: '^#?ClientAliveCountMax ', line: 'ClientAliveCountMax 2' }
      notify: Restart SSH

    - name: Asegurar que Firewalld esté instalado y activo
      dnf:
        name: firewalld
        state: present

    - name: Iniciar y habilitar servicio Firewalld
      systemd:
        name: firewalld
        state: started
        enabled: true


    - name: Asegurar que el servicio Auditd esté activo para auditoría de eventos
      systemd:
        name: auditd
        state: started
        enabled: true
        
handlers:
    - name: Restart SSH
      systemd:
        name: sshd
        state: restarted
