---
- name: Hardening y Seguridad Básica para Ubuntu
  hosts: all
  become: yes
  vars:

    nuevo_puerto_ssh: "2222"

  tasks:

    - name: Actualizar la caché de apt y aplicar upgrades de seguridad
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes


    - name: Cambiar puerto SSH y deshabilitar login de Root
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - { regexp: '^#?Port ', line: 'Port {{ nuevo_puerto_ssh }}' }
        - { regexp: '^#?PermitRootLogin ', line: 'PermitRootLogin no' }
        - { regexp: '^#?MaxAuthTries ', line: 'MaxAuthTries 3' }
      notify: Reiniciar SSH


    - name: Definir política por defecto del firewall (Bloquear Todo Entrante)
      ufw:
        direction: incoming
        policy: deny

    - name: Permitir tráfico saliente por defecto
      ufw:
        direction: outgoing
        policy: allow

    - name: Permitir el nuevo puerto SSH personalizado
      ufw:
        rule: allow
        port: "{{ nuevo_puerto_ssh }}"
        proto: tcp

    - name: Habilitar el Firewall (UFW)
      ufw:
        state: enabled


    - name: Instalar Fail2Ban y Actualizaciones Desatendidas
      apt:
        name:
          - fail2ban
          - unattended-upgrades
        state: present

    - name: Asegurar que Fail2Ban esté corriendo y habilitado
      service:
        name: fail2ban
        state: started
        enabled: yes

    - name: Habilitar las actualizaciones automáticas de seguridad
      copy:
        dest: /etc/apt/apt.conf.dir/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";


  handlers:
    - name: Reiniciar SSH
      service:
        name: ssh
        state: restarted
