---
- name: Hardening Básico para AlmaLinux
  hosts: [website]
  become: yes
  vars:
    ssh_port: "2222"
    allowed_ssh_users: "ometeotl"

  tasks:
    - name: Actualizar todos los paquetes del sistema a la última versión
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Configurar SSH seguro
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: '/usr/sbin/sshd -t -f %s'
      loop:
        - { regexp: '^#?Port', line: 'Port {{ ssh_port }}' }
        - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^#?X11Forwarding', line: 'X11Forwarding no' }
        - { regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 3' }
        - { regexp: '^#?AllowUsers', line: 'AllowUsers {{ allowed_ssh_users }}' }
      notify: Restart SSH

    - name: Asegurar que firewalld esté activo y habilitado
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Permitir el nuevo puerto SSH en el Firewall
      firewalld:
        port: "{{ ssh_port }}/tcp"
        zone: public
        state: enabled
        permanent: yes
        immediate: yes

    - name: Eliminar el servicio SSH por defecto (Puerto 22) del Firewall
      firewalld:
        service: ssh
        zone: public
        state: disabled
        permanent: yes
        immediate: yes

    - name: Mitigar ataques de red mediante Sysctl
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: 'net.ipv4.conf.all.accept_redirects', value: '0' }
        - { name: 'net.ipv4.conf.default.accept_redirects', value: '0' }
        - { name: 'net.ipv4.conf.all.secure_redirects', value: '0' }
        - { name: 'net.ipv4.conf.all.send_redirects', value: '0' }
        - { name: 'net.ipv4.conf.all.accept_source_route', value: '0' }
        - { name: 'net.ipv4.tcp_syncookies', value: '1' } # Protección contra SYN Flood

    - name: Restringir la ejecución en /dev/shm (Evita ejecución de exploits comunes)
      mount:
        path: /dev/shm
        src: tmpfs
        fstype: tmpfs
        opts: defaults,nodev,nosuid,noexec
        state: mounted


  handlers:
    - name: Restart SSH
      systemd:
        name: sshd
        state: restarted
